name: Integration Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.100"

      - name: Install dependencies
        working-directory: MySolution
        run: dotnet restore MySolution.sln

      - name: Build
        working-directory: MySolution
        run: dotnet build --no-restore
        
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Run Integration Tests
        working-directory: MySolution/IntegrationTests
        run: |
          dotnet test
